CREATE DATABASE rinhadb;

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

INSERT INTO public."__EFMigrationsHistory"
("MigrationId", "ProductVersion")
VALUES('20240207025439_InitialCreate', '8.0.1');

CREATE TABLE public."Clientes" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"Limite" int4 NOT NULL,
	"Saldoinicial" int8 NOT NULL,
	CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
);

INSERT INTO public."Clientes" ("Id","Limite","Saldoinicial") VALUES
	 (1,100000,0),
	 (2,80000,0),
	 (3,1000000,0),
	 (4,10000000,0),
	 (5,500000,0);

CREATE TABLE public."Transacoes" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"Valor" int8 NOT NULL,
	"Tipo" varchar(1) NOT NULL,
	"Descricao" varchar(100) NOT NULL,
	"IdCliente" int4 NULL,
	"Realizada_em" timestamptz NOT NULL,
	CONSTRAINT "PK_Transacoes" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Transacoes_Clientes_IdCliente" FOREIGN KEY ("IdCliente") REFERENCES public."Clientes"("Id")
);
CREATE INDEX "IX_Transacoes_IdCliente" ON public."Transacoes" USING btree ("IdCliente");
